### PR TITLE
adding error spans indicator in search results table

### PR DESCRIPTION
**Pull request by vsen**

### CODE REVIEW

**Comment by adriancole** [comment]
screen shot por favor?

**Comment by vsen** [comment]
Off you go 😃 
image

**Comment by ashishagg** [comment]
lets make it a practice and share the screenshots with every UI change. Tagging our UI-teers to follow it.
@absrivastava @bulicekj

**Comment by adriancole** [comment]
do you think the error count is telling? I was curious because it is hard to dedupe errors unless you have an operation that fans out

**Comment by vsen** [comment]
Error count here is simply count of spans that have error tag/log, out of the total number of spans. Client and server spans are counted separately. As you said, dedupe-ing is not that straightforward and this count might not match up with everyones mental model. 

That said, I think showing up a count is a good visual indicator(call-for-action) for users. Only showing root errors does not help in cases where some intermediate level gulped some error.

**Comment by adriancole** [comment]
I think your logic is sound about presence of error. Just wondering if count is necessary or not.

Ex red if root failed, orange if any failed (but not root)

**Comment by vsen** [comment]
Associating colors with state is not something users will understand quickly(unless you have a glossary), it could end-up being a hidden feature. Thats why I think showing count would be helpful. Do you have any better way of counting errors?

**Comment by vsen** [comment]
Seeing the error count is pretty intuitive for the users. I believe this is a good starting point, we can work on improving error count logic later.

**Comment by adriancole** [comment]
sure it is also a source of questions though. We are asked about every
number :P

anyway good thing about code is easy to change. go for it!

>

**Pull request merged**
