### PR TITLE
zipkin support for serviceGraph

### PR DESCRIPTION
**Pull request by adriancole**
working with @tacigar here at LINE

### CODE REVIEW

**Comment by adriancole** [comment]
It is very hard to get the server working in dev mode with connection to zipkin because `npm run start:dev` expects the configuration to be mock (or fails unit tests).

The way to get things started is to run `npm run start:dev`, then only after it is started, apply the diff.

```diff
diff --git a/server/config/base.js b/server/config/base.js
index 6e6b264..c03940e 100644
--- a/server/config/base.js
+++ b/server/config/base.js
@@ -36,7 +36,8 @@ module.exports = {
             //             zipkin connector expects a zipkin config field specifying zipkin api url,
             //             eg. zipkinUrl: 'http://<zipkin>/api/v2'}
             //  - stub - a stub used during development, will be removed in future
-            connectorName: 'stub'
+            connectorName: 'zipkin',
+            zipkinUrl: 'http://localhost:9411/api/v2'
         },
         trends: {
             // name of config connector module to use for fetching trends data from downstream
@@ -78,8 +79,9 @@ module.exports = {
             // - haystack - gets data from haystack-service-graph
             //              you must specify serviceGraphUrl
             //              e.g. serviceGraphUrl: 'https://<haystack>/serviceGraph'
-            connectorName: 'stub',
-            windowSizeInSecs: 3600
+            connectorName: 'zipkin',
+            zipkinUrl: 'http://localhost:9411/api/v2',
+            windowSizeInSecs: 86400
         }
     },
     timeWindowPresetOptions: [
```

**Comment by adriancole** [comment]
Right now the service graph works, but only if you enter a specific date. if you don't white screen with error. We are guessing maybe there needs to be some data populated, such as calls=0 when there are no results..

http://localhost:8080/search?time.from=1446348180000&time.to=1541046214657&tabId=serviceGraph

screen shot 2018-11-01 at 1 25 39 pm

**Comment by adriancole** [comment]
Changed the code to re-use haystack's connected graph splitter. I uploaded a netflix trace and now you can see two tabs: one for each connected graph:

screen shot 2018-11-01 at 2 00 44 pm


screen shot 2018-11-01 at 2 00 52 pm

**Comment by adriancole** [comment]
so status: we are happy with learning so far. will wait for feedback and also appreciate any help if someone wants to get this past the finish line. Notably, there's still a problem where if the search returns no results, the UI white screens

**Comment by vsen** [comment]
Added a fix for the UI issue when search results are null - https://github.com/ExpediaDotCom/haystack-ui/pull/422. 
Checking the rest of the code. Regarding dev mode run with Zipkin backend, that was a know limitation, will check if something better can be done for this.

**Comment by adriancole** [comment]
@vsen thanks for the support here.. I will progress this in the next day or two

**Comment by vsen** [comment]
@adriancole Change looks fine to me. Do you think you are done from your end, or is it good to merge?

**Comment by adriancole** [comment]
one sec.. lemme rebase and check it out

**Comment by adriancole** [comment]
@tacigar FYI I just updated the code based on a little drift and fixed the unit tests.

@vsen maybe ok if passes I guess!

**Pull request merged**
